; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "LoLLMs_webUI"
#define MyAppVersion "6.0"
#define MyAppPublisher "ParisNeo"
#define MyAppURL "https://parisneo.github.io/lollms-webui/"
#define MyAppExeName "win_run.bat"
#define MyAppUpdateModelsName "win_update_models.bat"
#define MyAppCondaSessionName "win_conda_session.bat"
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1A757D39-4C63-4E0C-AED3-BA6273BBC0CA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={%USERPROFILE}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=.\lollms-webui\LICENSE
InfoBeforeFile=.\lollms-webui\CODE_OF_CONDUCT.md
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename=lollms_v6_cpu
SetupIconFile=.\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\logo.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\logo.ico"
Name: "{autodesktop}\{#MyAppUpdateModelsName}"; Filename: "{app}\{#MyAppUpdateModelsName}"; Tasks: desktopicon; IconFilename: "{app}\logo.ico"
Name: "{commondesktop}\{#MyAppUpdateModelsName}"; Filename: "{app}\{#MyAppUpdateModelsName}"; IconFilename: "{app}\logo.ico"
Name: "{autodesktop}\{#MyAppCondaSessionName}"; Filename: "{app}\{#MyAppCondaSessionName}"; Tasks: desktopicon; IconFilename: "{app}\logo.ico"
Name: "{commondesktop}\{#MyAppCondaSessionName}"; Filename: "{app}\{#MyAppCondaSessionName}"; IconFilename: "{app}\logo.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

