############################################
### Create new discussion
############################################
GET http://localhost:9600/new_discussion
Content-Type: application/json

{
    "title": "Some title" // Can be empty
}
############################################
### List discussions
############################################
GET http://localhost:9600/list_discussions
############################################
### Load Discussion by ID
############################################
POST http://localhost:9600/load_discussion
Content-Type: application/json

{"id": 1}
############################################
### Delete Discussion by ID
############################################
POST http://localhost:9600/delete_discussion
Content-Type: application/json

{
    "id": 0 
}
############################################
### Edit discussion title
############################################
POST http://localhost:9600/edit_title
Content-Type: application/json

{
    "id": 0, // Discussion ID Must be integer
    "title": "New title"
}
############################################
### Update message
############################################
GET http://localhost:9600/update_message
?id=0 
&message="New Message text"
############################################
### Update setting
############################################
POST http://localhost:9600/update_setting
Content-Type: application/json

{
    "setting_name": "personality_language",
    "setting_value": "english"
}
############################################
### execute code
############################################
POST http://localhost:9600/execute_python_code
Content-Type: application/json

{
    "code": "print('hello world')"
}
############################################
### Get all personalities
############################################
GET http://localhost:9600/get_all_personalities
############################################
### Get current personality
############################################
GET http://localhost:9600/get_current_personality
############################################
### Get current personality infos
############################################
GET http://localhost:9600/get_current_personality_path_infos
############################################
### Mount personality
############################################
POST http://localhost:9600/mount_personality
Content-Type: application/json

{
    "language": "english",
    "category": "generic",
    "folder": "lollms"
}
############################################
### Unmount personality
############################################
POST http://localhost:9600/unmount_personality
Content-Type: application/json

{
    "language": "english",
    "category": "generic",
    "folder": "lollms"
}
############################################
### Select personality
############################################
POST http://localhost:9600/select_personality
Content-Type: application/json

{
    "id": 0 // Array index from get_config.personalities array
}

############################################
### Get personality settings
############################################
POST http://localhost:9600/get_personality_settings
Content-Type: application/json

{
    "language": "english",
    "category": "data",
    "folder": "text2bulletpoints"
}

############################################
### Install model from path
############################################
GET http://localhost:9600/install_model_from_path

############################################
### Get active personality settings
############################################
GET http://localhost:9600/get_active_personality_settings

############################################
### Get active binding settings
############################################
GET http://localhost:9600/get_active_binding_settings



####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
###
### INFORMATION SECTION
###
####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
####@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


############################################
### List Models
############################################
GET http://localhost:9600/list_models
############################################
### Get avaliable Models
############################################
GET http://localhost:9600/get_available_models
############################################
### List Bindings
############################################
GET http://localhost:9600/list_bindings
############################################
### Get Config
############################################
GET http://localhost:9600/get_config
############################################
### Get generation status
############################################
GET http://localhost:9600/get_generation_status
############################################
### Get disk usage
############################################
GET http://localhost:9600/disk_usage
############################################
### Get ram usage
############################################
GET http://localhost:9600/ram_usage

############################################
### Get vram usage
############################################
GET http://localhost:9600/vram_usage